### ISSUE TITLE
Windows 64bit build - segmentation fault at start.

### ISSUE THREAD

**Issue by viewizard** [viewizard/astromenace#27]
Tested Windows 64bit build - MSYS2+MinGW 64bit.
Segmentation fault at game start (looks like some init or VFS issue), need investigate this more carefully.

**Comment by viewizard** [comment]
Ok, I fount initial issue in XML parser
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000000043419e in viewizard::cXMLDocument::ParseTagContent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, viewizard::sXMLEntry*) [clone .part.0] ()
(gdb) t
Undefined command: "".  Try "help".
(gdb) bt
#0  0x000000000043419e in viewizard::cXMLDocument::ParseTagContent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, viewizard::sXMLEntry*) [clone .part.0] ()
#1  0x00000000004347e2 in viewizard::cXMLDocument::ParseTagContent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, viewizard::sXMLEntry*) [clone .part.0] ()
#2  0x00000000004347e2 in viewizard::cXMLDocument::ParseTagContent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, viewizard::sXMLEntry*) [clone .part.0] ()
#3  0x0000000000434fb6 in viewizard::cXMLDocument::cXMLDocument(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
    ()
#4  0x000000000051fc2a in viewizard::astromenace::cMissionScript::RunScript(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float) ()
#5  0x00000000004659ff in viewizard::astromenace::InitMenu(viewizard::astromenace::eMenuStatus) ()
#6  0x0000000000449b2f in SDL_main ()
#7  0x0000000000525e7a in main_getcmdline ()
#8  0x00000000004013c1 in __tmainCRTStartup ()
    at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:333
#9  0x00000000004014d6 in WinMainCRTStartup ()
    at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:186
```
connected to `unsigned long` type using for store string position date instead of `std::string::size_type`. Working on other Windows 64bit related build issues now.
